### ISSUE TITLE
files in config.cfg are not found

### ISSUE THREAD

**Issue by feiyuehchen** [AMAAI-Lab/MidiCaps#1]
Hi, thank you for the great works! I have two questions for the current repo: 
1. When I tried to run the scripts, I couldn't find the files in the [config.cfg](https://github.com/AMAAI-Lab/MidiCaps/blob/main/config.cfg) instead of the instrumentmap.
```
[DEFAULT]
genre_model="mtg_jamendo_genre-discogs-effnet-1.pb"
genre_metadata="mtg_jamendo_genre-discogs-effnet-1.json" 
mood_model="mtg_jamendo_moodtheme-discogs-effnet-1.pb"
mood_metadata="mtg_jamendo_moodtheme-discogs-effnet-1.json"
emb_model="discogs-effnet-bs64-1.pb"
location_file='../all_files_list_random.json'
output_json_file='../all_files_output.json'
instrumentmap='instruments.csv'
```

Where could I download those files if they are available?

2. Since I would like to run it in my own environment (Python 3.10.14), I could not install chord-extractor. Reading pipeline.py, I found that this package only works in the "Audio Part." Does that mean that if I ONLY process MIDI files, I can ignore this package? Thank you.

P.s. In the README.md, it should be 
```
export ANTHROPIC_API_KEY=<your claude 3 key>
python caption_claude.py # not "captions"
```

**Comment by elchico1990** [comment]
Hi, thanks for pointing out the missing links for genre and mood models. You can find them in the following links.

- genre model and metadata : https://essentia.upf.edu/models/classification-heads/mtg_jamendo_genre/
- mood model and metadata : https://essentia.upf.edu/models/classification-heads/mtg_jamendo_moodtheme/
- emb model : https://essentia.upf.edu/models/music-style-classification/discogs-effnet/

Regarding the python version, chard-extractor is not supported in 3.10. I recommend you create a conda env with python 3.9. Please note, audio part refers to https://github.com/AMAAI-Lab/MidiCaps/blob/17ceeb72ed1e339013e6fc7d70789fcf75023077/pipeline.py#L260 So, if you skip that part, you will not have mood, genre and chord summary. I will suggest you keep these features, but if you do not want them, then also it's okay. 

Thanks again for pointing out the typos. We will add the links to genre, mood models etc in readme. Hope this helps. Feel free to ask if you have further queries.

**Comment by elchico1990** [comment]
closing this as the issues are fixed.
