### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by asigalov61** [AMAAI-Lab/MidiCaps#2]
Hey AMAAI team :)

First of all, I wanted to thank you for creating and sharing this MidiCaps dataset! Its very nice and will be very useful for my projects :)

Secondly, I wanted to ask you if you would consider incorporating description/captions based on songs lyrics? 
LAKH MIDI Dataset contains a lot of songs for which there are lyrics available.

Incorporating lyrics captions/summaries would allow creation of the models or search/recommendation systems that would be based on the song description which would produce better results.

I have created and tested such dataset and system/model here:
https://huggingface.co/spaces/asigalov61/Music-Sentence-Transformer

Check it out! I think it may give you some new ideas and/or inspiration :)

I also would be happy to colab on something like that if you are interested.

Sincerely,

Alex

**Comment by dorienh** [comment]
Hi Alex,

Definitely interested. Perhaps it would be easy to add lyrics as a feature
in MidiCaps for those available. Happy to discuss more on collaboration,
perhaps we can discuss over email.

**Comment by asigalov61** [comment]
@dorienh Thank you for your response :)

I will email you shortly :)

Alex.
